- hosts: localhost
  vars:
    project_name: "{{ lookup('env', 'PROJECT_NAME') }}"  # Use environment variable
    branch_name: "{{ lookup('env', 'BRANCH_NAME') }}"  # Use environment variable
    commit_number: "{{ lookup('env', 'COMMIT_NUMBER') }}"  # Use environment variable
    s3_bucket: "{{ project_name | lower }}-{{ branch_name | lower }}-bucket"
    image_key: "{{ project_name | lower }}-{{ branch_name | lower }}-image-{{ ansible_date_time.date }}.img"
    region: "{{ lookup('env', 'AWS_REGION') }}"  # Use environment variable

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes

    - name: Install required dependencies
      apt:
        name:
          - quilt
          - qemu-user-static
          - debootstrap
          - libarchive-tools
          - qemu-utils
        state: present
      become: yes

    - name: Clone the Cyberdeck repository
      git:
        repo: 'https://github.com/wocsa/cyberdeck.git'
        dest: './cyberdeck'
        version: "{{ branch_name }}"

    - name: Capture the current date
      command: date +%Y-%m-%d
      register: current_date

    - name: Set the current date as a fact
      set_fact:
        current_date: "{{ current_date_output.stdout }}"

    - name: Run build script
      shell: cd ./cyberdeck && ./build.sh
      become: yes
      become_user: root
      register: build_script_output

    - name: Unzip to extract the raw image
      unarchive:
        src: "./cyberdeck/deploy/image_{{ current_date }}-cyberdeck-lite.zip"
        dest: "./cyberdeck/deploy/"
        remote_src: yes


    - name: Create an S3 bucket
      amazon.aws.s3_bucket:
        name: "{{ s3_bucket }}"
        region: "{{ region }}"
        state: present
        tags:
          Project: "{{ project_name }}"
          GitBranch: "{{ branch_name }}"
          CommitNumber: "{{ commit_number }}"

    - name: Upload the raw image to S3
      amazon.aws.s3_object:
        bucket: "{{ s3_bucket }}"
        key: "{{ image_key }}"
        src: "./cyberdeck/deploy/{{ current_date }}-cyberdeck-lite.img"
        region: "{{ region }}"
        mode: put
        tags:
          Project: "{{ project_name }}"
          GitBranch: "{{ branch_name }}"
          CommitNumber: "{{ commit_number }}"

    - name: Import image as AMI
      shell: |
        aws ec2 import-image --region {{ region }} --description "{{ project_name }}-{{ branch_name }}-ami" --disk-containers "Format=raw,UserBucket={S3Bucket={{ s3_bucket }},S3Key={{ image_key }}}" --tag-specifications "ResourceType=image,Tags=[{Key=Project,Value={{ project_name }}},{Key=GitBranch,Value={{ branch_name }}},{Key=CommitNumber,Value={{ commit_number }}}]"
      register: import_task_result



    - name: Output import task details
      debug:
        msg: "Import task started. Details: {{ import_task_result.stdout }}"
